# Generated by Django 6.0.6 on 2026-06-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
